# -*- mode: dockerfile -*-
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Dockerfile to build libmxnet.so, and a python wheel for the Jetson TX1/TX2
# This script assumes /work/mxnet exists and contains the mxnet code you wish to compile and
# that /work/build exists and is the target for your output.

FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04

ENV ARCH=aarch64 \
    HOSTCC=gcc \
    TARGET=ARMV8

WORKDIR /usr/local

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    git \
    wget \
    zip \
    unzip \
    python3 \
    python3-pip \
    awscli \
    crossbuild-essential-arm64 \
 && rm -rf /var/lib/apt/lists/*

COPY toolchains/aarch64-linux-gnu-toolchain.cmake /usr
ENV CMAKE_TOOLCHAIN_FILE=/usr/aarch64-linux-gnu-toolchain.cmake

RUN git clone --recursive -b v0.3.12 https://github.com/xianyi/OpenBLAS.git && \
    cd /usr/local/OpenBLAS && \
    make NOFORTRAN=1 CC=aarch64-linux-gnu-gcc && \
    make PREFIX=/usr/aarch64-linux-gnu install && \
    cd /usr/local && \
    rm -rf OpenBLAS

# Install aarch64 cross depedencies based on Jetpack 5.0.2

RUN wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/n/nsight-compute/nsight-compute-addon-l4t-2021.2.5_2021.2.5.2-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-cudart/cuda-driver-cross-aarch64-11-4_11.4.243-1_all.deb && \
    dpkg -i --force-all *.deb && \
    rm *.deb && \
    apt-get update && \
    apt-get install -y -f

RUN wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-thrust/cuda-cccl-cross-aarch64-11-4_11.4.222-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-cudart/cuda-cudart-cross-aarch64-11-4_11.4.243-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-nsight-compute-addon-l4t-11-4/cuda-nsight-compute-addon-l4t-11-4_11.4.14-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-nvcc/cuda-nvcc-cross-aarch64-11-4_11.4.239-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-nvml-dev/cuda-nvml-cross-aarch64-11-4_11.4.239-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-profiler-api/cuda-profiler-api-cross-aarch64-11-4_11.4.239-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/libc/libcudla/libcudla-cross-aarch64-11-4_11.4.239-1_all.deb && \
    dpkg -i --force-all *.deb && \
    rm *.deb && \
    apt-get install -y -f

RUN wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-cross-aarch64-11-4/cuda-cross-aarch64-11-4_11.4.14-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-cross-aarch64/cuda-cross-aarch64_11.4.14-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/libc/libcufft/libcufft-cross-aarch64-11-4_10.6.0.143-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-cupti/cuda-cupti-cross-aarch64-11-4_11.4.239-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/libc/libcurand/libcurand-cross-aarch64-11-4_10.2.5.238-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/libc/libcusolver/libcusolver-cross-aarch64-11-4_11.2.0.238-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/libc/libcusparse/libcusparse-cross-aarch64-11-4_11.6.0.238-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-cudart/cuda-driver-cross-aarch64-11-4_11.4.243-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/libn/libnpp/libnpp-cross-aarch64-11-4_11.4.0.228-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/c/cuda-nvrtc/cuda-nvrtc-cross-aarch64-11-4_11.4.239-1_all.deb && \
    wget https://repo.download.nvidia.com/jetson/x86_64/focal/pool/main/libc/libcublas/libcublas-cross-aarch64-11-4_11.6.6.23-1_all.deb && \
    dpkg -i *.deb && \
    rm *.deb && \
    apt-get install -y -f && \
    apt-get install -y cuda-cross-aarch64 cuda-cross-aarch64-11-4 && \
    rm -rf /var/lib/apt/lists/*

RUN cmake_version=3.25.1 && \
    cmake_url=https://github.com/Kitware/CMake/releases/download/v$cmake_version/cmake-$cmake_version-Linux-x86_64.sh && \
    cmake_install_script=/tmp/cmake-install.sh && \
    cmake_dir=/opt/cmake-$cmake_version && \
    wget "$cmake_url" -q -O "$cmake_install_script" && \
    chmod u+x "$cmake_install_script" && \
    mkdir "$cmake_dir" && \
    "$cmake_install_script" --skip-license --prefix="$cmake_dir" && \
    rm "$cmake_install_script" && \
    ln -s "$cmake_dir"/bin/* /usr/local/bin

ARG USER_ID=0
ARG GROUP_ID=0
COPY install/ubuntu_adduser.sh /work/
RUN /work/ubuntu_adduser.sh

COPY runtime_functions.sh /work/
WORKDIR /work/mxnet
